server:
  port: 8081
  servlet:
    context-path: /neo-service

spring:
  profiles:
    active: dev,service

# elasticsearch 配置
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: localhost:9300

#  freemarker:
#    check-template-location: true
#    cache: false
#    suffix: .ftl
#    settings:
#      template_update_delay: 0
#    template-loader-path: classpath:/templates/
#    charset: UTF-8
#    content-type: text/html
#    expose-session-attributes: true
#    expose-request-attributes: true
#    request-context-attribute: request

#关闭缓存 Thymeleaf 默认是开启页面缓存的 需要关闭这个页面缓存 否则会有缓存，导致页面没法及时看到更新后的效果
#  thymeleaf:
#    cache: false
#    prefix: classpath:/templates
#    suffix: .html
#    mode: HTML
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
#    check-template-location: true

mybatis:
  type-aliases-package: com.xsw.neo.service.model.entity
  mapper-locations: classpath*:com/xsw/neo/service/mapper/xml/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:log4j2.xml
  level:
    com.xsw.neo.service.mapper: trace